export const LANGUAGES = [
	{
		region: "af-ZA",
		name: "南非荷兰语（南非）",
		voices: ["AdriNeural(女)", "WillemNeural(男)"],
	},
	{
		region: "am-ET",
		name: "阿姆哈拉语（埃塞俄比亚）",
		voices: ["MekdesNeural(女)", "AmehaNeural(男)"],
	},
	{
		region: "ar-AE",
		name: "阿拉伯语（阿拉伯联合酋长国）",
		voices: ["FatimaNeural(女)", "HamdanNeural(男)"],
	},
	{
		region: "ar-BH",
		name: "阿拉伯语（巴林）",
		voices: ["LailaNeural(女)", "AliNeural(男)"],
	},
	{
		region: "ar-DZ",
		name: "阿拉伯语（阿尔及利亚）",
		voices: ["AminaNeural(女)", "IsmaelNeural(男)"],
	},
	{
		region: "ar-EG",
		name: "阿拉伯语（埃及）",
		voices: ["SalmaNeural(女)", "ShakirNeural(男)"],
	},
	{
		region: "ar-IQ",
		name: "阿拉伯语（伊拉克）",
		voices: ["RanaNeural(女)", "BasselNeural(男)"],
	},
	{
		region: "ar-JO",
		name: "阿拉伯语（约旦）",
		voices: ["SanaNeural(女)", "TaimNeural(男)"],
	},
	{
		region: "ar-KW",
		name: "阿拉伯语（科威特）",
		voices: ["NouraNeural(女)", "FahedNeural(男)"],
	},
	{
		region: "ar-LB",
		name: "阿拉伯语（黎巴嫩）",
		voices: ["LaylaNeural(女)", "RamiNeural(男)"],
	},
	{
		region: "ar-LY",
		name: "阿拉伯语（利比亚）",
		voices: ["ImanNeural(女)", "OmarNeural(男)"],
	},
	{
		region: "ar-MA",
		name: "阿拉伯语（摩洛哥）",
		voices: ["MounaNeural(女)", "JamalNeural(男)"],
	},
	{
		region: "ar-OM",
		name: "阿拉伯语（阿曼）",
		voices: ["AyshaNeural(女)", "AbdullahNeural(男)"],
	},
	{
		region: "ar-QA",
		name: "阿拉伯语（卡塔尔）",
		voices: ["AmalNeural(女)", "MoazNeural(男)"],
	},
	{
		region: "ar-SA",
		name: "阿拉伯语(沙特阿拉伯)",
		voices: ["ZariyahNeural(女)", "HamedNeural(男)"],
	},
	{
		region: "ar-SY",
		name: "阿拉伯语（叙利亚）",
		voices: ["AmanyNeural(女)", "LaithNeural(男)"],
	},
	{
		region: "ar-TN",
		name: "阿拉伯语（突尼斯）",
		voices: ["ReemNeural(女)", "HediNeural(男)"],
	},
	{
		region: "ar-YE",
		name: "阿拉伯语（也门）",
		voices: ["MaryamNeural(女)", "SalehNeural(男)"],
	},
	{
		region: "az-AZ",
		name: "阿塞拜疆语(拉丁语，阿塞拜疆)",
		voices: ["BanuNeural(女)", "BabekNeural(男)"],
	},
	{
		region: "bg-BG",
		name: "保加利亚语(保加利亚)",
		voices: ["KalinaNeural(女)", "BorislavNeural(男)"],
	},
	{
		region: "bn-BD",
		name: "孟加拉语（孟加拉国）",
		voices: ["NabanitaNeural(女)", "PradeepNeural(男)"],
	},
	{
		region: "bn-IN",
		name: "孟加拉语（印度）",
		voices: ["TanishaaNeural(女)", "BashkarNeural(男)"],
	},
	{
		region: "bs-BA",
		name: "波斯尼亚语（波斯尼亚和黑塞哥维那）",
		voices: ["VesnaNeural(女)", "GoranNeural(男)"],
	},
	{
		region: "ca-ES",
		name: "加泰罗尼亚语",
		voices: ["JoanaNeural(女)", "EnricNeural(男)", "AlbaNeural(女)"],
	},
	{
		region: "cs-CZ",
		name: "捷克语(捷克)",
		voices: ["VlastaNeural(女)", "AntoninNeural(男)"],
	},
	{
		region: "cy-GB",
		name: "威尔士语（英国）",
		voices: ["NiaNeural(女)", "AledNeural(男)"],
	},
	{
		region: "da-DK",
		name: "丹麦语（丹麦）",
		voices: ["ChristelNeural(女)", "JeppeNeural(男)"],
	},
	{
		region: "de-AT",
		name: "德语（奥地利）",
		voices: ["IngridNeural(女)", "JonasNeural(男)"],
	},
	{
		region: "de-CH",
		name: "德语（瑞士）",
		voices: ["LeniNeural(女)", "JanNeural(男)"],
	},
	{
		region: "de-DE",
		name: "德语（德国）",
		voices: [
			"KatjaNeural(女)",
			"ConradNeural(男)",
			"AmalaNeural(女)",
			"BerndNeural(男)",
			"ChristophNeural(男)",
			"ElkeNeural(女)",
			"GiselaNeural(女性、儿童)",
			"KasperNeural(男)",
			"KillianNeural(男)",
			"KlarissaNeural(女)",
			"KlausNeural(男)",
			"LouisaNeural(女)",
			"MajaNeural(女)",
			"RalfNeural(男)",
			"TanjaNeural(女)",
			"FlorianMultilingualNeural(男)",
			"SeraphinaMultilingualNeural(女)",
		],
	},
	{
		region: "el-GR",
		name: "希腊语(希腊)",
		voices: ["AthinaNeural(女)", "NestorasNeural(男)"],
	},
	{
		region: "en-AU",
		name: "英语（澳大利亚）",
		voices: [
			"NatashaNeural(女)",
			"WilliamNeural(男)",
			"AnnetteNeural(女)",
			"CarlyNeural(女)",
			"DarrenNeural(男)",
			"DuncanNeural(男)",
			"ElsieNeural(女)",
			"FreyaNeural(女)",
			"JoanneNeural(女)",
			"KenNeural(男)",
			"KimNeural(女)",
			"NeilNeural(男)",
			"TimNeural(男)",
			"TinaNeural(女)",
		],
	},
	{
		region: "en-CA",
		name: "英语（加拿大）",
		voices: ["ClaraNeural(女)", "LiamNeural(男)"],
	},
	{
		region: "en-GB",
		name: "英语（英国）",
		voices: [
			"SoniaNeural(女)",
			"RyanNeural(男)",
			"LibbyNeural(女)",
			"AbbiNeural(女)",
			"AlfieNeural(男)",
			"BellaNeural(女)",
			"ElliotNeural(男)",
			"EthanNeural(男)",
			"HollieNeural(女)",
			"MaisieNeural(女性、儿童)",
			"NoahNeural(男)",
			"OliverNeural(男)",
			"OliviaNeural(女)",
			"ThomasNeural(男)",
		],
	},
	{
		region: "en-HK",
		name: "英语（香港特別行政区）",
		voices: ["YanNeural(女)", "SamNeural(男)"],
	},
	{
		region: "en-IE",
		name: "英语（爱尔兰）",
		voices: ["EmilyNeural(女)", "ConnorNeural(男)"],
	},
	{
		region: "en-IN",
		name: "英语（印度）",
		voices: ["NeerjaNeural(女)", "PrabhatNeural(男)"],
	},
	{
		region: "en-KE",
		name: "英语（肯尼亚）",
		voices: ["AsiliaNeural(女)", "ChilembaNeural(男)"],
	},
	{
		region: "en-NG",
		name: "英语（尼日利亚）",
		voices: ["EzinneNeural(女)", "AbeoNeural(男)"],
	},
	{
		region: "en-NZ",
		name: "英语（新西兰）",
		voices: ["MollyNeural(女)", "MitchellNeural(男)"],
	},
	{
		region: "en-PH",
		name: "英语（菲律宾）",
		voices: ["RosaNeural(女)", "JamesNeural(男)"],
	},
	{
		region: "en-SG",
		name: "英语（新加坡）",
		voices: ["LunaNeural(女)", "WayneNeural(男)"],
	},
	{
		region: "en-TZ",
		name: "英语（坦桑尼亚）",
		voices: ["ImaniNeural(女)", "ElimuNeural(男)"],
	},
	{
		region: "en-US",
		name: "英语（美国）",
		voices: [
			"AvaNeural(女)",
			"AndrewNeural(男)",
			"EmmaNeural(女)",
			"BrianNeural(男)",
			"JennyNeural(女)",
			"GuyNeural(男)",
			"AriaNeural(女)",
			"DavisNeural(男)",
			"JaneNeural(女)",
			"JasonNeural(男)",
			"SaraNeural(女)",
			"TonyNeural(男)",
			"NancyNeural(女)",
			"AmberNeural(女)",
			"AnaNeural(女性、儿童)",
			"AshleyNeural(女)",
			"BrandonNeural(男)",
			"ChristopherNeural(男)",
			"CoraNeural(女)",
			"ElizabethNeural(女)",
			"EricNeural(男)",
			"JacobNeural(男)",
			"JennyMultilingualNeural(女)",
			"MichelleNeural(女)",
			"MonicaNeural(女)",
			"RogerNeural(男)",
			"RyanMultilingualNeural(男)",
			"SteffanNeural(男)",
			"AIGenerateNeural(男)",
			"AIGenerateNeural(女)",
			"AndrewMultilingualNeural(男)",
			"AvaMultilingualNeural(女)",
			"BlueNeural(中性)",
			"BrianMultilingualNeural(男)",
			"EmmaMultilingualNeural(女)",
			"AlloyMultilingualNeural(男)",
			"EchoMultilingualNeural(男)",
			"FableMultilingualNeural(中性)",
			"OnyxMultilingualNeural(男)",
			"NovaMultilingualNeural(女)",
			"ShimmerMultilingualNeural(女)",
			"AlloyMultilingualNeuralHD(男)",
			"EchoMultilingualNeuralHD(男)",
			"FableMultilingualNeuralHD(中性)",
			"OnyxMultilingualNeuralHD(男)",
			"NovaMultilingualNeuralHD(女)",
			"ShimmerMultilingualNeuralHD(女)",
		],
	},
	{
		region: "en-ZA",
		name: "英语（南非）",
		voices: ["LeahNeural(女)", "LukeNeural(男)"],
	},
	{
		region: "es-AR",
		name: "西班牙语（阿根廷）",
		voices: ["ElenaNeural(女)", "TomasNeural(男)"],
	},
	{
		region: "es-BO",
		name: "西班牙语（玻利维亚）",
		voices: ["SofiaNeural(女)", "MarceloNeural(男)"],
	},
	{
		region: "es-CL",
		name: "西班牙语（智利）",
		voices: ["CatalinaNeural(女)", "LorenzoNeural(男)"],
	},
	{
		region: "es-CO",
		name: "西班牙语（哥伦比亚）",
		voices: ["SalomeNeural(女)", "GonzaloNeural(男)"],
	},
	{
		region: "es-CR",
		name: "西班牙语（哥斯达黎加）",
		voices: ["MariaNeural(女)", "JuanNeural(男)"],
	},
	{
		region: "es-CU",
		name: "西班牙语（古巴）",
		voices: ["BelkysNeural(女)", "ManuelNeural(男)"],
	},
	{
		region: "es-DO",
		name: "西班牙语（多米尼加共和国）",
		voices: ["RamonaNeural(女)", "EmilioNeural(男)"],
	},
	{
		region: "es-EC",
		name: "西班牙语（厄瓜多尔）",
		voices: ["AndreaNeural(女)", "LuisNeural(男)"],
	},
	{
		region: "es-ES",
		name: "西班牙语(西班牙)",
		voices: [
			"ElviraNeural(女)",
			"AlvaroNeural(男)",
			"AbrilNeural(女)",
			"ArnauNeural(男)",
			"DarioNeural(男)",
			"EliasNeural(男)",
			"EstrellaNeural(女)",
			"IreneNeural(女)",
			"LaiaNeural(女)",
			"LiaNeural(女)",
			"NilNeural(男)",
			"SaulNeural(男)",
			"TeoNeural(男)",
			"TrianaNeural(女)",
			"VeraNeural(女)",
			"XimenaNeural(女)",
		],
	},
	{
		region: "es-GQ",
		name: "西班牙语（赤道几内亚）",
		voices: ["TeresaNeural(女)", "JavierNeural(男)"],
	},
	{
		region: "es-GT",
		name: "西班牙语（危地马拉）",
		voices: ["MartaNeural(女)", "AndresNeural(男)"],
	},
	{
		region: "es-HN",
		name: "西班牙语（洪都拉斯）",
		voices: ["KarlaNeural(女)", "CarlosNeural(男)"],
	},
	{
		region: "es-MX",
		name: "西班牙语(墨西哥)",
		voices: [
			"DaliaNeural(女)",
			"JorgeNeural(男)",
			"BeatrizNeural(女)",
			"CandelaNeural(女)",
			"CarlotaNeural(女)",
			"CecilioNeural(男)",
			"GerardoNeural(男)",
			"LarissaNeural(女)",
			"LibertoNeural(男)",
			"LucianoNeural(男)",
			"MarinaNeural(女)",
			"NuriaNeural(女)",
			"PelayoNeural(男)",
			"RenataNeural(女)",
			"YagoNeural(男)",
		],
	},
	{
		region: "es-NI",
		name: "西班牙（尼加拉瓜）",
		voices: ["YolandaNeural(女)", "FedericoNeural(男)"],
	},
	{
		region: "es-PA",
		name: "西班牙语（巴拿马）",
		voices: ["MargaritaNeural(女)", "RobertoNeural(男)"],
	},
	{
		region: "es-PE",
		name: "西班牙语（秘鲁）",
		voices: ["CamilaNeural(女)", "AlexNeural(男)"],
	},
	{
		region: "es-PR",
		name: "西班牙语（波多黎各）",
		voices: ["KarinaNeural(女)", "VictorNeural(男)"],
	},
	{
		region: "es-PY",
		name: "西班牙语（巴拉圭）",
		voices: ["TaniaNeural(女)", "MarioNeural(男)"],
	},
	{
		region: "es-SV",
		name: "西班牙语（萨尔瓦多）",
		voices: ["LorenaNeural(女)", "RodrigoNeural(男)"],
	},
	{
		region: "es-US",
		name: "西班牙语（美国）",
		voices: ["PalomaNeural(女)", "AlonsoNeural(男)"],
	},
	{
		region: "es-UY",
		name: "西班牙语（乌拉圭）",
		voices: ["ValentinaNeural(女)", "MateoNeural(男)"],
	},
	{
		region: "es-VE",
		name: "西班牙语（委内瑞拉）",
		voices: ["PaolaNeural(女)", "SebastianNeural(男)"],
	},
	{
		region: "et-EE",
		name: "爱沙尼亚语(爱沙尼亚)",
		voices: ["AnuNeural(女)", "KertNeural(男)"],
	},
	{
		region: "eu-ES",
		name: "巴斯克语",
		voices: ["AinhoaNeural(女)", "AnderNeural(男)"],
	},
	{
		region: "fa-IR",
		name: "波斯语（伊朗）",
		voices: ["DilaraNeural(女)", "FaridNeural(男)"],
	},
	{
		region: "fi-FI",
		name: "芬兰语（芬兰）",
		voices: ["SelmaNeural(女)", "HarriNeural(男)", "NooraNeural(女)"],
	},
	{
		region: "fil-PH",
		name: "菲律宾语（菲律宾）",
		voices: ["BlessicaNeural(女)", "AngeloNeural(男)"],
	},
	{
		region: "fr-BE",
		name: "法语（比利时）",
		voices: ["CharlineNeural(女)", "GerardNeural(男)"],
	},
	{
		region: "fr-CA",
		name: "法语（加拿大）",
		voices: [
			"SylvieNeural(女)",
			"JeanNeural(男)",
			"AntoineNeural(男)",
			"ThierryNeural(男)",
		],
	},
	{
		region: "fr-CH",
		name: "法语（瑞士）",
		voices: ["ArianeNeural(女)", "FabriceNeural(男)"],
	},
	{
		region: "fr-FR",
		name: "法语（法国）",
		voices: [
			"DeniseNeural(女)",
			"HenriNeural(男)",
			"AlainNeural(男)",
			"BrigitteNeural(女)",
			"CelesteNeural(女)",
			"ClaudeNeural(男)",
			"CoralieNeural(女)",
			"EloiseNeural(女性、儿童)",
			"JacquelineNeural(女)",
			"JeromeNeural(男)",
			"JosephineNeural(女)",
			"MauriceNeural(男)",
			"YvesNeural(男)",
			"YvetteNeural(女)",
			"RemyMultilingualNeural(男)",
			"VivienneMultilingualNeural(女)",
		],
	},
	{
		region: "ga-IE",
		name: "爱尔兰语（爱尔兰）",
		voices: ["OrlaNeural(女)", "ColmNeural(男)"],
	},
	{
		region: "gl-ES",
		name: "加利西亚语",
		voices: ["SabelaNeural(女)", "RoiNeural(男)"],
	},
	{
		region: "gu-IN",
		name: "古吉拉特语（印度）",
		voices: ["DhwaniNeural(女)", "NiranjanNeural(男)"],
	},
	{
		region: "he-IL",
		name: "希伯来语（以色列）",
		voices: ["HilaNeural(女)", "AvriNeural(男)"],
	},
	{
		region: "hi-IN",
		name: "印地语（印度）",
		voices: ["SwaraNeural(女)", "MadhurNeural(男)"],
	},
	{
		region: "hr-HR",
		name: "克罗地亚语（克罗地亚）",
		voices: ["GabrijelaNeural(女)", "SreckoNeural(男)"],
	},
	{
		region: "hu-HU",
		name: "匈牙利语(匈牙利)",
		voices: ["NoemiNeural(女)", "TamasNeural(男)"],
	},
	{
		region: "hy-AM",
		name: "亚美尼亚语（亚美尼亚）",
		voices: ["AnahitNeural(女)", "HaykNeural(男)"],
	},
	{
		region: "id-ID",
		name: "印度尼西亚语(印度尼西亚)",
		voices: ["GadisNeural(女)", "ArdiNeural(男)"],
	},
	{
		region: "is-IS",
		name: "冰岛语(冰岛)",
		voices: ["GudrunNeural(女)", "GunnarNeural(男)"],
	},
	{
		region: "it-IT",
		name: "意大利语（意大利）",
		voices: [
			"ElsaNeural(女)",
			"IsabellaNeural(女)",
			"DiegoNeural(男)",
			"BenignoNeural(男)",
			"CalimeroNeural(男)",
			"CataldoNeural(男)",
			"FabiolaNeural(女)",
			"FiammaNeural(女)",
			"GianniNeural(男)",
			"ImeldaNeural(女)",
			"IrmaNeural(女)",
			"LisandroNeural(男)",
			"PalmiraNeural(女)",
			"PierinaNeural(女)",
			"RinaldoNeural(男)",
			"GiuseppeNeural(男)",
		],
	},
	{
		region: "ja-JP",
		name: "日语（日本）",
		voices: [
			"NanamiNeural(女)",
			"KeitaNeural(男)",
			"AoiNeural(女)",
			"DaichiNeural(男)",
			"MayuNeural(女)",
			"NaokiNeural(男)",
			"ShioriNeural(女)",
			"MasaruMultilingualNeural(男)",
		],
	},
	{
		region: "jv-ID",
		name: "爪哇语(拉丁语、印度尼西亚)",
		voices: ["SitiNeural(女)", "DimasNeural(男)"],
	},
	{
		region: "ka-GE",
		name: "格鲁吉亚语（格鲁吉亚）",
		voices: ["EkaNeural(女)", "GiorgiNeural(男)"],
	},
	{
		region: "kk-KZ",
		name: "哈萨克语（哈萨克斯坦）",
		voices: ["AigulNeural(女)", "DauletNeural(男)"],
	},
	{
		region: "km-KH",
		name: "高棉语(柬埔寨)",
		voices: ["SreymomNeural(女)", "PisethNeural(男)"],
	},
	{
		region: "kn-IN",
		name: "卡纳达语（印度）",
		voices: ["SapnaNeural(女)", "GaganNeural(男)"],
	},
	{
		region: "ko-KR",
		name: "韩语(韩国)",
		voices: [
			"SunHiNeural(女)",
			"InJoonNeural(男)",
			"BongJinNeural(男)",
			"GookMinNeural(男)",
			"JiMinNeural(女)",
			"SeoHyeonNeural(女)",
			"SoonBokNeural(女)",
			"YuJinNeural(女)",
			"HyunsuNeural(男)",
		],
	},
	{
		region: "lo-LA",
		name: "老挝语(老挝)",
		voices: ["KeomanyNeural(女)", "ChanthavongNeural(男)"],
	},
	{
		region: "lt-LT",
		name: "立陶宛语(立陶宛)",
		voices: ["OnaNeural(女)", "LeonasNeural(男)"],
	},
	{
		region: "lv-LV",
		name: "拉脱维亚语(拉脱维亚)",
		voices: ["EveritaNeural(女)", "NilsNeural(男)"],
	},
	{
		region: "mk-MK",
		name: "马其顿语（北马其顿）",
		voices: ["MarijaNeural(女)", "AleksandarNeural(男)"],
	},
	{
		region: "ml-IN",
		name: "马拉雅拉姆语（印度）",
		voices: ["SobhanaNeural(女)", "MidhunNeural(男)"],
	},
	{
		region: "mn-MN",
		name: "蒙古语（蒙古）",
		voices: ["YesuiNeural(女)", "BataaNeural(男)"],
	},
	{
		region: "mr-IN",
		name: "马拉地语（印度）",
		voices: ["AarohiNeural(女)", "ManoharNeural(男)"],
	},
	{
		region: "ms-MY",
		name: "马来语（马来西亚）",
		voices: ["YasminNeural(女)", "OsmanNeural(男)"],
	},
	{
		region: "mt-MT",
		name: "马耳他语（马耳他）",
		voices: ["GraceNeural(女)", "JosephNeural(男)"],
	},
	{
		region: "my-MM",
		name: "缅甸语(缅甸)",
		voices: ["NilarNeural(女)", "ThihaNeural(男)"],
	},
	{
		region: "nb-NO",
		name: "书面挪威语（挪威）",
		voices: ["PernilleNeural(女)", "FinnNeural(男)", "IselinNeural(女)"],
	},
	{
		region: "ne-NP",
		name: "尼泊尔语（尼泊尔）",
		voices: ["HemkalaNeural(女)", "SagarNeural(男)"],
	},
	{
		region: "nl-BE",
		name: "荷兰语（比利时）",
		voices: ["DenaNeural(女)", "ArnaudNeural(男)"],
	},
	{
		region: "nl-NL",
		name: "荷兰语（荷兰）",
		voices: ["FennaNeural(女)", "MaartenNeural(男)", "ColetteNeural(女)"],
	},
	{
		region: "pl-PL",
		name: "波兰语（波兰）",
		voices: ["AgnieszkaNeural(女)", "MarekNeural(男)", "ZofiaNeural(女)"],
	},
	{
		region: "ps-AF",
		name: "普什图语（阿富汗）",
		voices: ["LatifaNeural(女)", "GulNawazNeural(男)"],
	},
	{
		region: "pt-BR",
		name: "葡萄牙语（巴西）",
		voices: [
			"FranciscaNeural(女)",
			"AntonioNeural(男)",
			"BrendaNeural(女)",
			"DonatoNeural(男)",
			"ElzaNeural(女)",
			"FabioNeural(男)",
			"GiovannaNeural(女)",
			"HumbertoNeural(男)",
			"JulioNeural(男)",
			"LeilaNeural(女)",
			"LeticiaNeural(女)",
			"ManuelaNeural(女)",
			"NicolauNeural(男)",
			"ValerioNeural(男)",
			"YaraNeural(女)",
			"ThalitaNeural(女)",
		],
	},
	{
		region: "pt-PT",
		name: "葡萄牙语(葡萄牙)",
		voices: ["RaquelNeural(女)", "DuarteNeural(男)", "FernandaNeural(女)"],
	},
	{
		region: "ro-RO",
		name: "罗马尼亚语(罗马尼亚)",
		voices: ["AlinaNeural(女)", "EmilNeural(男)"],
	},
	{
		region: "ru-RU",
		name: "俄语（俄罗斯）",
		voices: ["SvetlanaNeural(女)", "DmitryNeural(男)", "DariyaNeural(女)"],
	},
	{
		region: "si-LK",
		name: "僧伽罗语(斯里兰卡)",
		voices: ["ThiliniNeural(女)", "SameeraNeural(男)"],
	},
	{
		region: "sk-SK",
		name: "斯洛伐克语（斯洛伐克）",
		voices: ["ViktoriaNeural(女)", "LukasNeural(男)"],
	},
	{
		region: "sl-SI",
		name: "斯洛文尼亚语（斯洛文尼亚）",
		voices: ["PetraNeural(女)", "RokNeural(男)"],
	},
	{
		region: "so-SO",
		name: "索马里语（索马里）",
		voices: ["UbaxNeural(女)", "MuuseNeural(男)"],
	},
	{
		region: "sq-AL",
		name: "阿尔巴尼亚语（阿尔巴尼亚）",
		voices: ["AnilaNeural(女)", "IlirNeural(男)"],
	},
	{
		region: "sr-LATN-RS",
		name: "塞尔维亚语(拉丁语，塞尔维亚共和国)",
		voices: ["NicholasNeural(男)", "SophieNeural(女)"],
	},
	{
		region: "sr-RS",
		name: "塞尔维亚语(西里尔文，塞尔维亚)",
		voices: ["SophieNeural(女)", "NicholasNeural(男)"],
	},
	{
		region: "su-ID",
		name: "巽他语（印度尼西亚）",
		voices: ["TutiNeural(女)", "JajangNeural(男)"],
	},
	{
		region: "sv-SE",
		name: "瑞典语（瑞典）",
		voices: ["SofieNeural(女)", "MattiasNeural(男)", "HilleviNeural(女)"],
	},
	{
		region: "sw-KE",
		name: "斯瓦希里语（肯尼亚）",
		voices: ["ZuriNeural(女)", "RafikiNeural(男)"],
	},
	{
		region: "sw-TZ",
		name: "斯瓦希里语（坦桑尼亚）",
		voices: ["RehemaNeural(女)", "DaudiNeural(男)"],
	},
	{
		region: "ta-IN",
		name: "泰米尔语（印度）",
		voices: ["PallaviNeural(女)", "ValluvarNeural(男)"],
	},
	{
		region: "ta-LK",
		name: "泰米尔语（斯里兰卡）",
		voices: ["SaranyaNeural(女)", "KumarNeural(男)"],
	},
	{
		region: "ta-MY",
		name: "泰米尔语（马来西亚）",
		voices: ["KaniNeural(女)", "SuryaNeural(男)"],
	},
	{
		region: "ta-SG",
		name: "泰米尔语（新加坡）",
		voices: ["VenbaNeural(女)", "AnbuNeural(男)"],
	},
	{
		region: "te-IN",
		name: "泰卢固语（印度）",
		voices: ["ShrutiNeural(女)", "MohanNeural(男)"],
	},
	{
		region: "th-TH",
		name: "泰语（泰国）",
		voices: ["PremwadeeNeural(女)", "NiwatNeural(男)", "AcharaNeural(女)"],
	},
	{
		region: "tr-TR",
		name: "土耳其语 (Türkiye)",
		voices: ["EmelNeural(女)", "AhmetNeural(男)"],
	},
	{
		region: "uk-UA",
		name: "乌克兰语(乌克兰)",
		voices: ["PolinaNeural(女)", "OstapNeural(男)"],
	},
	{
		region: "ur-IN",
		name: "乌尔都语（印度）",
		voices: ["GulNeural(女)", "SalmanNeural(男)"],
	},
	{
		region: "ur-PK",
		name: "乌尔都语（巴基斯坦）",
		voices: ["UzmaNeural(女)", "AsadNeural(男)"],
	},
	{
		region: "uz-UZ",
		name: "乌兹别克语(拉丁语，乌兹别克斯坦)",
		voices: ["MadinaNeural(女)", "SardorNeural(男)"],
	},
	{
		region: "vi-VN",
		name: "越南语(越南)",
		voices: ["HoaiMyNeural(女)", "NamMinhNeural(男)"],
	},
	{
		region: "wuu-CN",
		name: "中文（吴语，简体）",
		voices: ["XiaotongNeural(女)", "YunzheNeural(男)"],
	},
	{
		region: "yue-CN",
		name: "中文（粤语，简体）",
		voices: ["XiaoMinNeural(女)", "YunSongNeural(男)"],
	},
	{
		region: "zh-CN",
		name: "中文（普通话，简体）",
		voices: [
			"XiaoxiaoNeural(女)",
			"YunxiNeural(男)",
			"YunjianNeural(男)",
			"XiaoyiNeural(女)",
			"YunyangNeural(男)",
			"XiaochenNeural(女)",
			"XiaohanNeural(女)",
			"XiaomengNeural(女)",
			"XiaomoNeural(女)",
			"XiaoqiuNeural(女)",
			"XiaoruiNeural(女)",
			"XiaoshuangNeural(女性、儿童)",
			"XiaoyanNeural(女)",
			"XiaoyouNeural(女性、儿童)",
			"XiaozhenNeural(女)",
			"YunfengNeural(男)",
			"YunhaoNeural(男)",
			"YunxiaNeural(男)",
			"YunyeNeural(男)",
			"YunzeNeural(男)",
			"XiaochenMultilingualNeural(女)",
			"XiaorouNeural(女)",
			"XiaoxiaoDialectsNeural(女)",
			"XiaoxiaoMultilingualNeural(女)",
			"XiaoyuMultilingualNeural(女)",
			"YunjieNeural(男)",
			"YunyiMultilingualNeural(男)",
		],
	},
	{
		region: "zh-CN-GUANGXI",
		name: "中文（广西口音普通话，简体）",
		voices: ["YunqiNeural，(男)"],
	},
	{
		region: "zh-CN-henan",
		name: "中文（中原官话河南，简体）",
		voices: ["YundengNeural(男)"],
	},
	{
		region: "zh-CN-liaoning",
		name: "中文（东北官话，简体）",
		voices: ["XiaobeiNeural，(女)", "YunbiaoNeural，(男)"],
	},
	{
		region: "zh-CN-shaanxi",
		name: "中文（中原官话陕西，简体）",
		voices: ["XiaoniNeural，(女)"],
	},
	{
		region: "zh-CN-shandong",
		name: "中文（冀鲁官话，简体）",
		voices: ["YunxiangNeural(男)"],
	},
	{
		region: "zh-CN-sichuan",
		name: "中文（西南普通话，简体）",
		voices: ["YunxiNeural，(男)"],
	},
	{
		region: "zh-HK",
		name: "中文(粤语，繁体)",
		voices: ["HiuMaanNeural(女)", "WanLungNeural(男)", "HiuGaaiNeural(女)"],
	},
	{
		region: "zh-TW",
		name: "中文（台湾普通话，繁体）",
		voices: [
			"HsiaoChenNeural(女)",
			"YunJheNeural(男)",
			"HsiaoYuNeural(女)",
		],
	},
	{
		region: "zu-ZA",
		name: "祖鲁语（南非）",
		voices: ["ThandoNeural(女)", "ThembaNeural(男)"],
	},
];
